### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'LinkedInAPI'

### ISSUE THREAD

**Issue by choupit0** [MrTuxx/SocialPwned#3]
Hello,

I read carefully your (F)Manual to install all the prerequisites and use your tool.

However I get this error message:

`AttributeError: module 'lib' has no attribute 'LinkedInAPI'`

![LinkedInAPI](https://user-images.githubusercontent.com/47336639/106171519-a00e2100-615f-11eb-96ac-1d86d2a7ff20.PNG)

FYI I'm using Python 3.6.8:

![LinkedInAPI2](https://user-images.githubusercontent.com/47336639/106171735-e95e7080-615f-11eb-95cf-9aa048cce377.PNG)

Do you have an idea? I forgot something?..

**Comment by MrTuxx** [comment]
Hello,

The problem I think is due to the Python version, the linkedin API works with python >= 3.6. But I have been testing on an Ubuntu 16.04.7 and I had the same problem. I recommend you to upgrade to python version 3.8 which I have verified that it works correctly, for this I followed the following steps:

```
apt-get install python3.8
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 4
update-alternatives --config python3
python3 -V
sudo apt remove python3-pip
apt-get install python3-pip
pip3 install -r requirements.txt
python3 socialpwned.py --help
```

If you update the Python version, let me know if it worked correctly to close the issue.

**Comment by choupit0** [comment]
Hello,

What a hell to upgrade Python to 3.8 version. It was necessary to re-install pip3, it was broken.

(https://bootstrap.pypa.io/get-pip.py)

Now your script is functionning. Thank you!
